app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about_page, name='about'),
    path('signup', views.signup_page, name='signup_page'),
    path('signin', views.signin_page, name='signin_page'),
    path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
    path('logout', views.logout_page, name='logout_page'),
]

urlpatterns += [
    path('account', views.account, name='account'),
    path('account/delete-account', views.delete_account, name='delete_account'),
    path('account/search_items', views.item_page, name='item'),
    path('account/profile_item/<str:id>', views.profile_item_page, name='profile_item'),
    path('account/favorite_items', views.favorite_items_page, name='favorite_items'),
]

urlpatterns += [
    path('change_password/', views.change_password, name='change_password'),
    # path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset-password/reset_password.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset-password/password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="reset-password/password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset-password/password_reset_done.html"), name='password_reset_complete')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from datetime import date

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from import_export import resources

from mptt.models import MPTTModel, TreeForeignKey

from .tasks import send_email_task
from . import managers


class User(AbstractUser):
    username = None
    department = models.CharField(max_length=100, default="department name")
    email = models.EmailField(_('email address'), unique=True)
    grant_access_to_this_account = models.BooleanField(default=False)
    notify_date = models.DateField(null=True, blank=True)
    expiration_date = models.DateField(null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = managers.UserManager()

    def clean(self):
        if self.expiration_date and self.notify_date:
            if self.expiration_date < self.notify_date:
                raise ValidationError('Notify time should be before send time')
        return super().clean()

    def save_base(self, raw=False, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.notify_date != '' and self.notify_date is not None:
            days = (self.expiration_date - self.notify_date).days
            send_email_task.apply_async(args=[self.username,
                                              self.email,
                                              self.expiration_date,
                                              days
                                              ], countdown=days * 86400)
        if (self.notify_date == '' or self.notify_date is None) and self.expiration_date:
            days = (self.expiration_date - date.today()).days
            send_email_task.apply_async(args=[self.username,
                                              self.email,
                                              self.expiration_date,
                                              days
                                              ], countdown=days * 86400)
        super().save_base(raw, force_insert, force_update, using, update_fields)


class Category(MPTTModel):
    name = models.CharField(max_length=200)
    parent = TreeForeignKey(to='self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Item(models.Model):
    id = models.CharField(max_length=200, primary_key=True)
    name = models.CharField(max_length=200)
    rank = models.IntegerField(null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    verified = models.BooleanField(null=True, blank=True)
    category = models.ManyToManyField(Category, blank=True, related_name='item')
    # updated_at = models.DateTimeField(auto_now=True)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['rank']


class Sample(models.Model):
    id = models.CharField(max_length=200, primary_key=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    date = models.DateField()
    name = models.CharField(max_length=200)
    text = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-added_at']

    def __str__(self):
        return f'{ self.item.name } -> { self.user.email }'

app/views.py
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib import messages
from django.template.loader import render_to_string
from django.core import serializers
from .forms import UserProfileForm
from project import settings

from app.models import User
from app.tokens import account_activation_token

from app.forms import SignUpForm, SignInForm, FavouriteItemForm, ChangePasswordForm
from .tasks import send_email_task
from . import models


def index(request):
    return render(request, 'index.html')


def about_page(request):
    return render(request, 'about.html')


def signup_page(request):
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            if not User.objects.filter(email=form.cleaned_data['email']).count():
                user = form.save()
                subject = 'Activate your account'
                current_site = get_current_site(request)
                message = render_to_string('activation-account.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                send_mail(subject, message, settings.EMAIL_HOST_USER, [form.data.get('email')])
                messages.add_message(
                    request=request,
                    level=messages.SUCCESS,
                    message="Please confirm your email, to activate your account"
                )

            else:
                messages.add_message(
                    request=request,
                    level=messages.ERROR,
                    message="Sorry, this mail already exists"
                )
        else:
            for msg in form.errors:
                messages.add_message(
                    request=request,
                    level=messages.ERROR,
                    message=form.errors[msg][0]
                )
    return render(request, 'signup-page.html', {'form': form})


def signin_page(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email=form.data.get('email')).first()
            if user:
                login(request, user)
                return redirect('index')
        else:
            return render(request, 'signin-page.html', {'form': form})
    return render(request, 'signin-page.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.add_message(
            request=request,
            level=messages.SUCCESS,
            message="Your account successfully activated!"
        )
        return redirect('index')
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required
def account(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=request.user.pk)
            user.first_name = form.data.get('first_name')
            user.last_name = form.data.get('last_name')
            user.department = form.data.get('department')
            user.save()

    return render(request, 'user/account.html', {'form': form})


@login_required
def item_page(request):
    if request.method == 'POST':

        form = FavouriteItemForm(request.POST)
        form.user = request.user

        if form.is_valid():
            form.save()

    if request.user.grant_access_to_this_account and (
            (datetime.date.today() < request.user.expiration_date) if request.user.expiration_date else False
    ):

        qs = models.Item.objects.all()

        c = {
            "min": qs.filter(quantity__isnull=False).order_by('quantity')[0].quantity if qs.filter(quantity__isnull=False).order_by('quantity').count() else 0,
            "max": qs.filter(quantity__isnull=False).order_by('quantity').reverse()[0].quantity if qs.filter(quantity__isnull=False).order_by('quantity').reverse().count() else 0,
            'favourite_form': FavouriteItemForm()
        }

        params = list(request.GET.keys())

        if 'min' in params and (not request.GET['min'] == ''):
            qs = qs.filter(quantity__gte=request.GET['min'])

        if 'max' in params and (not request.GET['max'] == ''):
            qs = qs.filter(quantity__lte=request.GET['max'])

        if 'verified' in params and request.GET['verified'] == 'on':
            qs = qs.filter(verified=True)

        if 'items_samples' in params and request.GET['items_samples'] == 'on':
            qs = qs.filter(sample__isnull=False)

        if request.GET.get('category') is not None:
            filter_category = request.GET.get('category')
            if filter_category != '':
                filter_categories = filter_category.split(', ')
                category = models.Category.objects.filter(name__in=filter_categories)
                qs = qs.filter(category__in=category).distinct()

        c['items'] = qs.distinct()
        c['has_access'] = True

        page = request.GET.get('page', 1)

        paginator = Paginator(c['items'], 20)
        try:
            c['items'] = paginator.page(page)
        except PageNotAnInteger:
            c['items'] = paginator.page(1)
        except EmptyPage:
            c['items'] = paginator.page(paginator.num_pages)
    else:
        c = {'has_access': False}

    categories = models.Category.objects.all()
    c['categories'] = categories
    # {'page_obj': page_obj}
    return render(request, 'user/tables.html', c)


@login_required
def profile_item_page(request, id):
    if request.method == 'POST':

        form = FavouriteItemForm(request.POST)
        form.user = request.user

        if form.is_valid():
            form.save()

    if request.user.grant_access_to_this_account and (
            (datetime.date.today() < request.user.expiration_date) if request.user.expiration_date else False
    ):

        c = {
            'favourite_form': FavouriteItemForm(),
            'has_access': True,
            'item': models.Item.objects.get(id=id),
        }

    else:
        c = {'has_access': False}

    return render(request, 'user/profile_items.html', c)


def favorite_items_page(request):
    if request.method == "POST":
        data = request.POST
        if data['action'] == 'remove_comment':
            if request.user.favourite_set.filter(item_id=data['item']).count():
                request.user.favourite_set.filter(item_id=data['item']).first().delete()

    c = {
        'items': request.user.favourite_set.all(),
        "has_access": request.user.grant_access_to_this_account
    }
    return render(request, 'user/table_favorite.html', c)


def reset_password(request):
    return render(request, 'reset-password.html')


def logout_page(request):
    logout(request)
    return redirect('index')


@login_required
def delete_account(request):
    u = request.user
    logout(request)
    models.User.objects.get(pk=u.pk).delete()
    messages.add_message(
        request=request,
        level=messages.SUCCESS,
        message="Your account successfully deleted"
    )
    return render(request, 'index.html')


@login_required
def change_password(request):
    c = {}

    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)

        user = models.User.objects.get(pk=request.user.pk)

        if form.is_valid():
            if user.check_password(form.cleaned_data['current_password']):
                if form.cleaned_data['new_password'] == form.cleaned_data['confirm_password']:
                    user.set_password(form.cleaned_data['confirm_password'])
                    user.save()

                    messages.add_message(
                        request=request,
                        level=messages.SUCCESS,
                        message="Your password has been changed"
                    )
                    return redirect('signin_page')
                else:
                    messages.add_message(
                        request=request,
                        level=messages.ERROR,
                        message="Passwords didn't match"
                    )
            else:
                messages.add_message(
                    request=request,
                    level=messages.ERROR,
                    message="Current password is incorrect"
                )
        else:
            messages.add_message(
                request=request,
                level=messages.ERROR,
                message="Sorry, please try again!"
            )
    else:
        c['form'] = ChangePasswordForm()

    return render(request, 'user/change_password.html', c)

templates/user/account.html
{% extends "base.html" %}
{% load i18n static %}


{% block content %}
    <main>
        <div class="container mt-4 mb-2">
            <div class="row">
                <div class="col-12 text-center">
                    <h2>{% trans 'Profile Information' %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-8 offset-2">
                    <form method="post" action="{% url 'account' %}">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputFirstName">First name</label>
                                <input type="text" name="first_name" class="form-control" id="inputFirstName" required
                                       value="{{ user.first_name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputLastName">Last name</label>
                                <input type="text" name="last_name" class="form-control" id="inputLastName" required
                                       value="{{ user.last_name }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputDepartment">Department</label>
                                <input type="text" name="department" class="form-control" id="inputDepartment"
                                       required value="{{ user.department }}">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                    <br>
                    <button class="btn btn-danger" id="delete_account">Delete account</button>
                </div>
            </div>
        </div>
    </main>

    <script>
    document.querySelector("#delete_account").addEventListener("click", function (e){
        e.preventDefault();
        const confirmed = confirm("Do you really want to delete your account?");

        if (confirmed) {
            window.location="{% url 'delete_account' %}"
        }
    })
    </script>
{% endblock %}

templates/user/change_password.html
{% extends "base.html" %}
{% load i18n static %}


{% block content %}
    <main>
        <div class="container mt-4 mb-2">
            <div class="row">
                <div class="offset-4 col-md-4 text-center">
                    <h2>{% trans 'Change password' %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="offset-2 col-8">

                    {% for message in messages %}
                        <div class="alert alert-{{ message.level_tag }}" role="alert">{{ message }}</div>
                    {% endfor %}

                </div>
            </div>
            <div class="row">
                <div class="col-8 offset-2">
                    <form method="post" action="{% url 'change_password' %}">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group offset-3 col-md-6">
                                <label for="current_password">Current password</label>
                                <input type="password" name="current_password" class="form-control" id="current_password" required value="{{ user.current_password }}">
                            </div>
                        </div>
                        <div class="form-group offset-3 col-md-6">
                            <hr>
                        </div>
                        <div class="form-row">
                            <div class="form-group offset-3 col-md-6">
                                <label for="new_password">New password</label>
                                <input type="password" name="new_password" class="form-control" id="new_password" required value="{{ user.new_password }}">
                            </div>
                            <div class="form-group offset-3 col-md-6">
                                <label for="confirm_password">Confirm new password</label>
                                <input type="password" name="confirm_password" class="form-control" id="confirm_password" required value="{{ user.confirm_password }}">
                            </div>
                        </div>

                        <div class="form-group offset-3 col-md-6">
                            <button type="submit" class="btn btn-primary d-block w-100">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

    <script>
    document.querySelector("#delete_account").addEventListener("click", function (e){
        e.preventDefault();
        const confirmed = confirm("Are you sure to delete account");

        if (confirmed) {
            window.location="{% url 'delete_account' %}"
        }
    })
    </script>
{% endblock %}

templates/user/profile_items.html
{% extends "base.html" %}
{% load i18n static app_tags %}

{% block content %}
    <div class="container">
        {% if has_access %}
            <div class="row">
                <div class="col-12">
                    <div>
                        <table class="table table-striped my-3">
                            <thead>
                            <tr>
                                <th scope="col">id</th>
                                <th scope="col">name</th>
                                <th scope="col">rank</th>
                                <th scope="col">quantity</th>
                                <th scope="col">verified</th>
                                <th scope="col">category</th>
{#                                <th scope="col">updated_at</th>#}
{#                                <th scope="col">created_at</th>#}
                                <th scope="col">Favourites</th>
                                <th scope="col">Samples</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ item.id }}</td>
                                <td>{{ item.name }}</td>
                                <td>{{ item.rank }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.verified }}</td>
                                <td>{{ item.category|display_cats }}</td>
{#                                <td>{{ item.updated_at }}</td>#}
{#                                <td>{{ item.created_at }}</td>#}
                                <td>
                                    {% with request.user.favourite_set.all|get_favourites as favourites %}
                                        {% if item not in favourites %}
                                            <form action="{% url 'profile_item' item.id %}" method="post">
                                                {% csrf_token %}

                                                <input type="hidden" name="user" id="id_user"
                                                       value="{{ request.user.id }}" required>
                                                <input type="hidden" name="item" id="id_item" value="{{ item.id }}"
                                                       required>
                                                <input type="hidden" name="action" value="add_comment">

                                                <button class="btn btn-success" type="submit"><i class="fa fa-plus"></i>
                                                </button>
                                                <input type="text" name="comment" id="id_comment"
                                                       placeholder="{% trans 'comments here' %}"
                                                       class="form-control d-inline-block align-middle"
                                                       style="width: auto;">
                                            </form>
                                        {% endif %}
                                    {% endwith %}
                                </td>
                                <td>
                                    <table class="table table-striped my-3">
                                        {#                                            <thead>#}
                                        {#                                            <tr>#}
                                        {#                                                <th scope="col">name</th>#}
                                        {#                                                <th scope="col">text</th>#}
                                        {#                                            </tr>#}
                                        {#                                            </thead>#}
                                        <tbody>
                                        {% for bullet in item.sample_set.all %}
                                            <tr>
                                                <td>{{ bullet.name }}</td>
                                                <td>{{ bullet.text }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-6">
                    <div>
                        <div class="pagination">
                            {% if items.has_other_pages %}
                                <ul class="pagination">
                                    {% if items.has_previous %}
                                        <li><a href="?page={{ items.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in items.paginator.page_range %}
                                        {% if items.number == i %}
                                            <li class="active"><span>{{ i }} <span
                                                    class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if items.has_next %}
                                        <li><a href="?page={{ items.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <h3 style="text-align: center; margin-top: 40px;">Sorry, you dont have access to Items</h3>
        {% endif %}
    </div>
{% endblock %}

templates/user/table_favorite.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}
    <div class="container">
    {% if has_access %}
        <div class="row">
            <div class="col-12">
                <h1 style="margin-top: 20px; text-align: center">Favorite Items</h1>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-12">
                <div>
                    <table class="table table-striped my-3">
                        <thead>
                            <tr>
                                <th scope="col">name</th>
                                <th scope="col">quantity</th>
                                <th scope="col">comment</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for item in items %}
                                <tr>
                                    <td><a href="{% url 'profile_item' item.item.id %}">{{ item.item.name }}</a></td>
                                    <td>{{ item.item.quantity }}</td>

                                    <td>
                                        {% if item.comment %}<span>{{ item.comment }}</span>{% endif %}
                                    </td>
                                    <td>
                                        <form action="{% url 'favorite_items' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="user" id="id_user" value="{{ request.user.id }}" required>
                                            <input type="hidden" name="item" id="id_item" value="{{ item.item.id }}" required>
                                            <input type="hidden" name="action" value="remove_comment">

                                            <input type="submit" class="btn btn-secondary" value="Remove">
                                        </form>
                                    </td>

                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
      {% else %}
            <h3 style="text-align: center; margin-top: 40px;">Sorry, you dont have access to Items</h3>
        {% endif %}
    </div>
{% endblock %}